version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: what2eat_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456          # Mật khẩu do bạn tự đặt lại ở đây
      POSTGRES_DB: what2eat_db           # Tên database sẽ được tạo tự động
    ports:
      - "5432:5432"                      # Map port ra ngoài localhost
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: